### ISSUE TITLE
"算出来的distance为562.5，记录到的XXX为720"这里的单位都是像素吗？

### ISSUE THREAD

**Issue by csonezp** [williamfzc/wx_jump#5]

**Comment by williamfzc** [comment]
562.5是像素
XXX是毫秒

**Comment by csonezp** [comment]
@williamfzc 嗯，但是这个distance是如何精确测出来的呢？

**Comment by williamfzc** [comment]
可以这样:

- 把apply_to_adb注释掉, 正常运行代码
- 可以看到打印出来的各项指标, x distance就是算出来的distance值.
- 计算方法为起始点与终点的两点距离

**Comment by csonezp** [comment]
@williamfzc thanks。
算出来mix2参数为：

DISTANCE_ARG = 1.44986098

DEVICE_SCREEN = (1080, 2160)
